# Generated by Django 4.2.26 on 2025-11-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_order', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_dramas', to='dramas.actor')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_actors', to='dramas.drama')),
            ],
            options={
                'verbose_name': 'Drama Actor Relationship',
                'verbose_name_plural': 'Drama Actor Relationships',
                'ordering': ['billing_order', 'actor__name'],
                'unique_together': {('drama', 'actor')},
            },
        ),
    ]
