# Generated by Django 4.2.26 on 2025-11-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0002_dramaactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dramaactor',
            options={'ordering': ['billing_order', 'actor'], 'verbose_name': 'Drama Actor Relationship', 'verbose_name_plural': 'Drama Actor Relationships'},
        ),
    ]
