# Generated by Django 4.2.26 on 2025-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0003_alter_dramaactor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dramaactor',
            options={'ordering': ['billing_order', 'actor__name'], 'verbose_name': 'Drama Actor Relationship', 'verbose_name_plural': 'Drama Actor Relationships'},
        ),
        migrations.AlterUniqueTogether(
            name='dramaactor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dramaactor',
            name='billing_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dramaactor',
            constraint=models.UniqueConstraint(fields=('drama', 'actor'), name='unique_drama_actor'),
        ),
    ]
